import io
import os
import platform
import subprocess

import github_to_sops


def run_checked(args):
    return subprocess.run(args, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)


def run_github_to_sops(args):
    return run_checked(["./github-to-sops", *args])


def current_gh_login():
    result = run_checked(["gh", "api", "user", "--jq", ".login"])
    login = result.stdout.strip()
    assert login, "gh returned empty login"
    return login


def assert_sops_yaml_has_keys(content, expected_user=None):
    assert "Generated by" in content
    assert github_to_sops.GITHUB_TO_SOPS_TAG in content
    assert "ssh-" in content
    if expected_user is not None:
        assert f"# {expected_user}" in content


def test_latest_sops_version_matches_newest_supported_major_gh_release():
    result = run_checked([
        "gh", "release", "list",
        "--repo", "getsops/sops",
        "--json", "tagName,isDraft,isPrerelease",
        "--jq", f"[.[] | select((.isDraft | not) and (.isPrerelease | not) and (.tagName | startswith(\"v{github_to_sops.SUPPORTED_SOPS_MAJOR}.\")))][0].tagName",
    ])
    expected = result.stdout.strip()

    assert expected.startswith(f"v{github_to_sops.SUPPORTED_SOPS_MAJOR}.")
    assert github_to_sops.get_latest_sops_version() == expected


def test_current_gh_identity_has_fetchable_public_keys():
    login = current_gh_login()

    keys = github_to_sops.fetch_github_ssh_keys([login])

    assert login in keys
    assert any(keys_for_type for keys_for_type in keys[login].values()), f"GitHub user {login} has no public SSH keys"


def test_cli_seeds_and_updates_sops_yaml_for_explicit_user(tmp_path):
    login = current_gh_login()
    sops_yaml = tmp_path / ".sops.yaml"

    seed = run_github_to_sops([
        "--github-users", login,
        "import-keys",
        "--format", "sops",
    ])
    sops_yaml.write_text(seed.stdout)
    assert_sops_yaml_has_keys(sops_yaml.read_text(), expected_user=login)

    run_github_to_sops([
        "--github-users", login,
        "import-keys",
        "--format", "sops",
        "--inplace-edit", str(sops_yaml),
    ])

    assert_sops_yaml_has_keys(sops_yaml.read_text(), expected_user=login)


def test_cli_seeds_and_updates_sops_yaml_for_repo_collaborators(tmp_path):
    owner_repo = github_to_sops.get_owner_repo(None, ".")
    assert owner_repo is not None
    collaborators = github_to_sops.fetch_collaborators(owner_repo)
    assert collaborators, f"No collaborators returned for {owner_repo}"

    sops_yaml = tmp_path / ".sops.yaml"

    seed = run_github_to_sops([
        "import-keys",
        "--format", "sops",
    ])
    sops_yaml.write_text(seed.stdout)
    seeded_content = sops_yaml.read_text()
    assert_sops_yaml_has_keys(seeded_content)
    assert any(f"# {collaborator}" in seeded_content for collaborator in collaborators)

    run_github_to_sops([
        "import-keys",
        "--format", "sops",
        "--inplace-edit", str(sops_yaml),
    ])

    updated_content = sops_yaml.read_text()
    assert_sops_yaml_has_keys(updated_content)
    assert any(f"# {collaborator}" in updated_content for collaborator in collaborators)


def test_download_sops_release_assets_verifies_checksum(tmp_path):
    version = github_to_sops.get_latest_sops_version()
    download_url = github_to_sops.get_sops_download_url(platform.system(), platform.machine(), version)
    assert download_url is not None

    binary_name = os.path.basename(download_url)
    binary_path, checksums_path = github_to_sops.download_sops_release_assets(
        version,
        binary_name,
        str(tmp_path),
    )

    assert os.path.exists(binary_path)
    assert os.path.exists(checksums_path)
    assert github_to_sops.verify_sha256(binary_path, checksums_path, binary_name)


def test_inplace_edit_inserts_imported_keys_into_existing_age_group():
    template = """creation_rules:
  - path_regex: secrets\\.enc\\.json$
    key_groups:
      - age:
        - age1exampleexistingrecipient # existing server recipient
"""
    output = io.StringIO()

    github_to_sops.print_keys(
        template=template.strip(),
        user_keys={"alice": {"ssh-ed25519": ["AAAATESTKEY"]}},
        accepted_key_types={"ssh-ed25519"},
        output_format="sops",
        output_fd=output,
    )

    assert output.getvalue() == """creation_rules:
  - path_regex: secrets\\.enc\\.json$
    key_groups:
      - age:
        - age1exampleexistingrecipient # existing server recipient
        # {generated_msg}
        - ssh-ed25519 AAAATESTKEY # alice
""".format(generated_msg=github_to_sops.GENERATED_MSG)


def test_import_keys_does_not_discover_or_download_sops(monkeypatch):
    login = current_gh_login()

    def fail_if_called(*args, **kwargs):
        raise AssertionError("non-install commands must not touch SOPS release lookup/download")

    monkeypatch.setattr(github_to_sops, "get_latest_sops_version", fail_if_called)
    monkeypatch.setattr(github_to_sops, "download_sops_release_assets", fail_if_called)

    github_to_sops.main([
        "--github-users", login,
        "import-keys",
        "--format", "sops",
    ])
